//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorServerDemo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorServerDemo.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @page &quot;/jstonet&quot;
        ///@inject IJSRuntime JS
        ///
        ///
        ///&lt;button class=&quot;btn btn-primary mb-3&quot; @onclick=&quot;ConvertArray&quot;&gt;Convert Array&lt;/button&gt;
        ///
        ///&lt;p&gt;
        ///    @text
        ///&lt;/p&gt;
        ///
        ///
        ///
        ///
        ///@code {
        ///
        ///    private MarkupString text;
        ///    private IJSObjectReference jsModule = null!;
        ///
        ///    private uint[] quoteArray =
        ///        new uint[]
        ///        {
        ///            60, 101, 109, 62, 67, 97, 110, 39, 116, 32, 115, 116, 111, 112, 32,
        ///            116, 104, 101, 32, 115, 105, 103, 110, 97, 108, 44, 32, 77, 97,
        ///            108, 46, 60, 47, 101, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string array {
            get {
                return ResourceManager.GetString("array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using BlazorServerDemo.Pages;
        ///
        ///namespace BlazorServerDemo.bUnit
        ///{
        ///    /// &lt;summary&gt;
        ///    /// These tests are written entirely in C#.
        ///    /// Learn more at https://bunit.dev/docs/getting-started/writing-tests.html#creating-basic-tests-in-cs-files
        ///    /// &lt;/summary&gt;
        ///    [TestClass]
        ///    public class CounterCSharpTests : BunitTestContext
        ///    {
        ///        [TestMethod]
        ///        public void CounterStartsAtZero()
        ///        {
        ///            // Arrange
        ///            var cut = RenderComponent&lt;Counter&gt;();
        ///
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bunit {
            get {
                return ResourceManager.GetString("bunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @page &quot;/forms&quot;
        ///@using BlazorServerDemo.Helpers
        ///@using BlazorServerDemo.Models
        ///@inject IToastService toastService
        ///
        ///&lt;PageTitle&gt;Blazor Server Demo: Form&lt;/PageTitle&gt;
        ///
        ///&lt;h2 class=&quot;mb-5&quot;&gt;Form Example&lt;/h2&gt;
        ///
        ///
        ///@if (formSuccess)
        ///{
        ///    &lt;p class=&quot;text-success&quot;&gt;Success! Your form was submitted succesfully.&lt;/p&gt;
        ///}
        ///
        ///&lt;EditForm EditContext=&quot;@editContext&quot; OnValidSubmit=&quot;@HandleValidSubmit&quot;&gt;
        ///    &lt;DataAnnotationsValidator /&gt;
        ///    &lt;ValidationSummary /&gt;
        ///
        ///    &lt;div class=&quot;row&quot;&gt;
        ///        &lt;div class=&quot;col-6&quot;&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @page &quot;/nettojs&quot;
        ///@implements IDisposable
        ///@inject IJSRuntime JS
        ///
        ///
        ///&lt;p&gt;Name: &lt;input @bind=&quot;name&quot; class=&quot;form-control&quot; /&gt;&lt;/p&gt;
        ///
        ///&lt;button class=&quot;btn btn-primary&quot; @onclick=&quot;TriggerDotNetInstanceMethod&quot;&gt;
        ///	Trigger .NET instance method
        ///&lt;/button&gt;
        ///
        ///&lt;p class=&quot;fw-bold mt-2&quot;&gt;Result: @result&lt;/p&gt;
        ///
        ///
        ///
        ///@code {
        ///
        ///    private string? name;
        ///    private string? result;
        ///    private DotNetObjectReference&lt;NetToJs&gt;? objRef;
        ///	
        ///	protected override void OnInitialized()
        ///    {
        ///        objRef = DotNetObjectReference.Cre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Instance {
            get {
                return ResourceManager.GetString("Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @page &quot;/nettojs&quot;
        ///@implements IDisposable
        ///@inject IJSRuntime JS
        ///
        ///
        ///
        ///&lt;p&gt;Name: &lt;input @bind=&quot;name&quot; class=&quot;form-control&quot; /&gt;&lt;/p&gt;
        ///
        ///&lt;button class=&quot;btn btn-primary mb-2&quot; onclick=&quot;GreetingHelpers.sayHello()&quot;&gt;
        ///     Trigger JS function - &lt;strong&gt;sayHello&lt;/strong&gt;
        ///&lt;/button&gt;
        ///
        ///&lt;button class=&quot;btn btn-primary mb-2&quot; onclick=&quot;GreetingHelpers.welcomeVisitor()&quot;&gt;
        ///     Trigger JS function - &lt;strong&gt;welcomeVisitor&lt;/strong&gt;
        ///&lt;/button&gt;
        ///
        ///
        ///@code {
        ///
        ///    private string? name;
        ///    private DotNetObjectReference&lt;NetToJs&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string multiple {
            get {
                return ResourceManager.GetString("multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button class=&quot;btn btn-primary mb-2&quot; onclick=&quot;returnArrayAsync()&quot;&gt;
        ///    Trigger .NET static method
        ///&lt;/button&gt;
        ///
        ///
        ///@code { 
        ///
        ///    [JSInvokable]
        ///    public static Task ReturnArrayAsync()
        ///    {
        ///        return Task.FromResult(new int[] { 1, 2, 3 });
        ///    }  
        ///
        ///}
        ///
        ///
        ///// JavaScript function located in app.js 
        ///
        ///window.returnArrayAsync = () =&gt; {
        ///    DotNet.invokeMethodAsync(&apos;BlazorServerDemo&apos;, &apos;ReturnArrayAsync&apos;)
        ///        .then(data =&gt; {
        ///            alert(data);
        ///        });
        ///};.
        /// </summary>
        internal static string StaticJS {
            get {
                return ResourceManager.GetString("StaticJS", resourceCulture);
            }
        }
    }
}
